INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34530, NULL, NULL, 'Майкудук', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34531, NULL, NULL, 'Михайловка', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34533, NULL, NULL, 'р-н ЖБИ', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34532, NULL, NULL, 'Пришахтинск', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (33534, NULL, NULL, 'р-н Нового рынка', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (33536, NULL, NULL, 'Юго-Восток', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (33538, NULL, NULL, 'Федоровка', 239, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34528, NULL, NULL, 'Илийский', 2, NULL, NULL, NULL, NULL, 'district', NULL);
INSERT INTO region (id, latitude, longitude, name, parentid_id, alias, leftkey, level, rightkey, type, zoom) VALUES (34529, NULL, NULL, 'Карасайский', 2, NULL, NULL, NULL, NULL, 'district', NULL);


INSERT INTO region_kn (id, key, name, regionid_id) VALUES (94, '37557679', 'Федоровка', 33538);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (78, '42874623', 'Алатауский', 3);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (80, '27671457', 'Ауэзовский', 29);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (81, '8916474', 'Бостандыкский', 73);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (82, '28538280', 'Жетысуский', 83);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (85, '28451689', 'Медеуский', 89);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (87, '28968815', 'Турксибский', 99);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (79, '9256312', 'Алмалинский', 26);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (86, '24800606', 'Наурызбайский', 783);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (83, '34366614', 'Илийский', 34528);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (84, '31419755', 'Карасайский', 34529);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (95, '2927387', 'Алматинский', 106);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (88, '2067403', 'Майкудук', 34530);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (89, '21618525', 'Михайловка', 34531);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (90, '26466238', 'Пришахтинск', 34532);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (91, '36231046', 'р-н ЖБИ', 34533);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (92, '37238760', 'р-н Нового рынка', 33534);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (96, '6309988', 'Сарыаркинский', 107);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (97, '26636760', 'Есильский', 291);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (98, '34191971', 'Косши', 731);
INSERT INTO region_kn (id, key, name, regionid_id) VALUES (93, '6776875', 'Юго-Восток', 33536);